# Generated by Django 3.0.7 on 2020-07-09 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200625_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='media',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
