# Generated by Django 3.0.7 on 2020-07-09 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='media',
            field=models.CharField(blank=True, max_length=100, verbose_name='头像'),
        ),
    ]
