# Generated by Django 3.0.7 on 2020-07-10 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_comment_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='media',
        ),
    ]
